// This file is autogenerated – run `ant apidocs` to update it

export interface AdyenPaymentResult {
     paymentId?: string;
     resultCode?: null | string;
     merchantReference?: null | string;
     pspReference?: null | string;
     refusalReason?: null | string;
     action?: null | AdyenAction;
     details?: AdyenPaymentDetail[];
}
